version: '3.9'
services:
  ted-search-logic:
    container_name: ted-search-logic
    hostname: ted-search-logic
    image: 644435390668.dkr.ecr.us-west-2.amazonaws.com/ofori-search-ted-search:2.1
    # build:
      # context: .
      # dockerfile: Dockerfile
    # restart: on-failure
    volumes:
      - static_files:/var/static_files
      - nginx_conf:/var/nginx/default.conf
    networks:
      - proxy-net
  
  proxy:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - static_files:/usr/share/nginx/static
      - nginx_conf:/etc/nginx/conf.d:ro
    # restart: always
    depends_on:
      - ted-search-logic
    networks:
      -  proxy-net
networks:
   proxy-net:

volumes:
  static_files:
  nginx_conf:
